from __future__ import annotations

import logging
import re
from collections import Counter

from config import settings

try:
    from groq import Groq
except Exception:  # noqa: BLE001
    Groq = None

try:
    from openai import OpenAI
except Exception:  # noqa: BLE001
    OpenAI = None

logger = logging.getLogger(__name__)

def get_summarization_prompt(text: str) -> str:
    return f"""
    Summarize the following document into a clean, visually appealing HTML format suitable for email.
    Keep it concise and highlight key points using headings, bullet points, and emphasis.

    Document:
    {text[:15000]}  # Truncate to avoid token limits
    """

async def summarize_document(text: str) -> str:
    """
    Summarizes the document text into HTML format using the configured LLM provider.
    """
    provider = settings.LLM_PROVIDER.lower()
    prompt = get_summarization_prompt(text)
    
    try:
        if provider == "groq" and Groq is not None:
            if not settings.GROQ_API_KEY:
                raise ValueError("GROQ_API_KEY not found in environment.")
            
            client = Groq(api_key=settings.GROQ_API_KEY)
            response = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[
                    {"role": "system", "content": "You are a professional assistant that generates HTML summaries of documents."},
                    {"role": "user", "content": prompt}
                ]
            )
            return response.choices[0].message.content

        elif provider == "openai" and OpenAI is not None:
            if not settings.OPENAI_API_KEY:
                raise ValueError("OPENAI_API_KEY not found in environment.")
            
            client = OpenAI(api_key=settings.OPENAI_API_KEY)
            response = client.chat.completions.create(
                model="gpt-4o",
                messages=[
                    {"role": "system", "content": "You are a professional assistant that generates HTML summaries of documents."},
                    {"role": "user", "content": prompt}
                ]
            )
            return response.choices[0].message.content
        
        return _fallback_html_summary(text)

        raise ValueError(f"Unsupported LLM provider: {provider}")

    except Exception as e:
        logger.warning(f"Falling back to local summary: {str(e)}")
        return _fallback_html_summary(text)


def _fallback_html_summary(text: str) -> str:
    sentences = [segment.strip() for segment in re.split(r"(?<=[.!?])\s+", text) if segment.strip()]
    if not sentences:
        sentences = [text.strip() or "No extractable text was found in the PDF."]

    word_counts = Counter(
        word.lower()
        for word in re.findall(r"[A-Za-z0-9']+", text)
        if len(word) > 3
    )
    key_terms = [word for word, _ in word_counts.most_common(5)]
    summary_sentences = sentences[:3]

    bullet_items = "".join(f"<li>{term}</li>" for term in key_terms) or "<li>Document reviewed successfully.</li>"
    paragraph_items = "".join(f"<p style=\"margin:8px 0;line-height:1.7;\">{sentence}</p>" for sentence in summary_sentences)

    return (
        '<div style="font-family: Arial, sans-serif; max-width: 700px; margin: auto; '
        'color: #1f2937; background:#f9fafb; padding: 32px; border-radius: 12px;">'
        '<h2 style="font-size:18px;color:#1d4ed8;margin:18px 0 6px;">Document Summary</h2>'
        f"{paragraph_items}"
        '<h2 style="font-size:18px;color:#1d4ed8;margin:18px 0 6px;">Key Terms</h2>'
        f'<ul style="padding-left:20px;margin:6px 0;">{bullet_items}</ul>'
        '<hr style="border:none;border-top:1px solid #e5e7eb;margin:28px 0;"/>'
        '<p style="font-size:12px;color:#6b7280;text-align:center;">Generated by Document Summarizer</p>'
        '</div>'
    )
