"""
utils/formatter.py — Convert plain text summary to email-friendly HTML
"""

import re


def text_to_html(summary: str) -> str:
    """
    Convert a structured plain-text summary produced by the LLM into
    clean, inline-styled HTML suitable for email clients.
    """

    lines = summary.strip().splitlines()
    html_parts: list[str] = []

    html_parts.append(
        """<div style="font-family: Arial, sans-serif; max-width: 700px;
            margin: auto; color: #1f2937; background:#f9fafb;
            padding: 32px; border-radius: 12px;">"""
    )

    in_ul = False

    for line in lines:
        stripped = line.strip()

        if not stripped:
            if in_ul:
                html_parts.append("</ul>")
                in_ul = False
            html_parts.append("<br/>")
            continue

        # Heading-level detection (markdown-style or labelled)
        if stripped.startswith("# "):
            if in_ul:
                html_parts.append("</ul>")
                in_ul = False
            text = stripped[2:].strip()
            html_parts.append(
                f'<h1 style="font-size:22px;color:#111827;margin-bottom:4px;">{text}</h1>'
            )

        elif stripped.startswith("## "):
            if in_ul:
                html_parts.append("</ul>")
                in_ul = False
            text = stripped[3:].strip()
            html_parts.append(
                f'<h2 style="font-size:18px;color:#1d4ed8;margin:18px 0 6px;">{text}</h2>'
            )

        elif stripped.startswith("### "):
            if in_ul:
                html_parts.append("</ul>")
                in_ul = False
            text = stripped[4:].strip()
            html_parts.append(
                f'<h3 style="font-size:15px;color:#374151;margin:12px 0 4px;">{text}</h3>'
            )

        # Bold label like "Title:", "Overview:", etc.
        elif re.match(r"^[A-Z][A-Za-z ]+:$", stripped):
            if in_ul:
                html_parts.append("</ul>")
                in_ul = False
            html_parts.append(
                f'<h2 style="font-size:17px;color:#1d4ed8;margin:20px 0 6px;">{stripped}</h2>'
            )

        # Bullet point
        elif stripped.startswith(("- ", "* ", "• ")):
            if not in_ul:
                html_parts.append(
                    '<ul style="padding-left:20px;margin:6px 0;">'
                )
                in_ul = True
            text = re.sub(r"^\s*[-*•]\s*", "", stripped)
            html_parts.append(
                f'<li style="margin-bottom:4px;line-height:1.6;">{text}</li>'
            )

        # Numbered list item
        elif re.match(r"^\d+\.", stripped):
            if not in_ul:
                html_parts.append(
                    '<ul style="padding-left:20px;margin:6px 0;list-style-type:decimal;">'
                )
                in_ul = True
            text = re.sub(r"^\d+\.\s*", "", stripped)
            html_parts.append(
                f'<li style="margin-bottom:4px;line-height:1.6;">{text}</li>'
            )

        # Normal paragraph
        else:
            if in_ul:
                html_parts.append("</ul>")
                in_ul = False
            html_parts.append(
                f'<p style="margin:8px 0;line-height:1.7;">{stripped}</p>'
            )

    if in_ul:
        html_parts.append("</ul>")

    # Footer
    html_parts.append(
        """<hr style="border:none;border-top:1px solid #e5e7eb;margin:28px 0;"/>
        <p style="font-size:12px;color:#6b7280;text-align:center;">
            Generated by Multi-Model AI Summarization API
        </p></div>"""
    )

    return "\n".join(html_parts)
